spring:
  application:
    name: itoken-zuul
  zipkin:
    base-url: http://localhost:9411
  main:
    allow-bean-definition-overriding: true
server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.12.157:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: hello-spring-cloud-web-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: hello-spring-cloud-web-admin-feign