spring:
  application:
    name: itoken-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/deleteI/iToken.git
          search-paths: serveConfig/respo
          username: deleteI
          password: 6453873.0chenyuhang
  zipkin:
    base-url: http://192.168.12.157:9411
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.12.157:8761/eureka/