spring:
  application:
    name: hello-spring-cloud-eureka

server:
  port: 8761
  zipkin:
    base-url: http://localhost:9411
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/