spring:
  application:
    name: itoken-eureka

server:
  port: 8761
  zipkin:
    base-url: http://192.168.12.157:9411
eureka:
  instance:
    hostname: 192.168.12.157
  client:
    # 表示是否将自己注册到集群中，由于是要注册到集群中，所有应该开启
    registerWithEureka: true
    # 集群的华为true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.12.157:8761/eureka/,http://192.168.12.157:8861/eureka/,http://192.168.12.157:8961/eureka/