spring:
  application:
    name: itoken-eureka

server:
  port: 8761
  zipkin:
    base-url: http://192.168.12.157:9411
eureka:
  instance:
    hostname: 192.168.12.157
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/